### ISSUE TITLE
Invalid processing/parsing of errors when executing requests

### ISSUE THREAD

**Issue by maxidor** [kamax-io/matrix-java-sdk#37]
```
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:224)
	at com.google.gson.Gson.fromJson(Gson.java:887)
	at com.google.gson.Gson.fromJson(Gson.java:852)
	at com.google.gson.Gson.fromJson(Gson.java:801)
	at com.google.gson.Gson.fromJson(Gson.java:773)
	at io.kamax.matrix.client.AMatrixHttpClient.createErrorInfo(AMatrixHttpClient.java:312)
	at io.kamax.matrix.client.AMatrixHttpClient.execute(AMatrixHttpClient.java:202)
	at io.kamax.matrix.client.AMatrixHttpClient.execute(AMatrixHttpClient.java:186)
	at io.kamax.matrix.client.regular.MatrixHttpClient.sync(MatrixHttpClient.java:159)
	at io.kamax.matrix.bots.send_n_leave.SendNLeaveBot.lambda$start$6(SendNLeaveBot.java:94)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:385)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:213)
	... 10 more
```

**Comment by MrCustomizer** [comment]
I've seen this error before. I don't know in which situation you are experiencing this. But I'm able to reproduce it by restarting my Synapse instance while being connected to it with Palaver. Related issue: https://github.com/MrCustomizer/palaver/issues/18
