### ISSUE TITLE
NPE when fetching name for user

### ISSUE THREAD

**Issue by maxidor** [kamax-io/matrix-java-sdk#39]
```
java.lang.NullPointerException
	at io.kamax.matrix.client.AMatrixHttpClient.extractAsStringFromBody(AMatrixHttpClient.java:317)
	at io.kamax.matrix.client.MatrixHttpUser.getName(MatrixHttpUser.java:62)
	at de.localtoast.palaver.sys.RoomRepository.fetchRoomName(RoomRepository.kt:87)
	at de.localtoast.palaver.sys.RoomRepository.prefetch(RoomRepository.kt:95)
	at de.localtoast.palaver.sys.events.MatrixEventProcessor.prefetch(MatrixEventProcessor.kt:99)
	at de.localtoast.palaver.sys.events.MatrixEventProcessor.access$prefetch(MatrixEventProcessor.kt:35)
	at de.localtoast.palaver.sys.events.MatrixEventProcessor$processNewEventsForRoom$1.invoke(MatrixEventProcessor.kt:84)
	at de.localtoast.palaver.sys.events.MatrixEventProcessor$processNewEventsForRoom$1.invoke(MatrixEventProcessor.kt:35)
	at tornadofx.FXTask.call(Async.kt:416)
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1423)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by MrCustomizer** [comment]
Newer versions of Palaver log these exceptions as errors to the console, including the matrix id where it happened. Perhaps this helps.
